// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCWgj2_xcJunIOaLHt-BCi65szGMt6u_o',
    appId: '1:665865941975:web:d2a83ba463f51f4c735192',
    messagingSenderId: '665865941975',
    projectId: 'aashayein-c1861',
    authDomain: 'aashayein-c1861.firebaseapp.com',
    storageBucket: 'aashayein-c1861.appspot.com',
    measurementId: 'G-N03FW33PW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu2f5Vn000aTiBLEuBi5_u97YHt1IMbXE',
    appId: '1:665865941975:android:39ba5fa31bc0b5c9735192',
    messagingSenderId: '665865941975',
    projectId: 'aashayein-c1861',
    storageBucket: 'aashayein-c1861.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAanzXAmxeDU5_ilKg3UjRqyxExGAPvBNc',
    appId: '1:665865941975:ios:081c938d6e4f37ca735192',
    messagingSenderId: '665865941975',
    projectId: 'aashayein-c1861',
    storageBucket: 'aashayein-c1861.appspot.com',
    androidClientId: '665865941975-3ntrh506uq8844bf3nh1hja9reci3v5p.apps.googleusercontent.com',
    iosClientId: '665865941975-hlbve0s4e3oeh98uvuqta9lrk7ucu131.apps.googleusercontent.com',
    iosBundleId: 'com.example.rehabcentre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAanzXAmxeDU5_ilKg3UjRqyxExGAPvBNc',
    appId: '1:665865941975:ios:081c938d6e4f37ca735192',
    messagingSenderId: '665865941975',
    projectId: 'aashayein-c1861',
    storageBucket: 'aashayein-c1861.appspot.com',
    androidClientId: '665865941975-3ntrh506uq8844bf3nh1hja9reci3v5p.apps.googleusercontent.com',
    iosClientId: '665865941975-hlbve0s4e3oeh98uvuqta9lrk7ucu131.apps.googleusercontent.com',
    iosBundleId: 'com.example.rehabcentre',
  );
}
